// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI_1gpxig9DJSb_eO0GIuNxmcD2-A27oI',
    appId: '1:1043660617455:web:4b277d94cad0b60aea0d1a',
    messagingSenderId: '1043660617455',
    projectId: 'first-app-c060d',
    authDomain: 'first-app-c060d.firebaseapp.com',
    databaseURL: 'https://first-app-c060d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-c060d.appspot.com',
    measurementId: 'G-MJZF46GE86',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuEME2vu_lxUgjmQdGhWP3xwR5HCNDVrA',
    appId: '1:1043660617455:android:96ee2f69c9353942ea0d1a',
    messagingSenderId: '1043660617455',
    projectId: 'first-app-c060d',
    databaseURL: 'https://first-app-c060d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-c060d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTSw5n0xGtB-o4Q4-sn_pqpnGNjs14HIA',
    appId: '1:1043660617455:ios:7ac962cc4c756254ea0d1a',
    messagingSenderId: '1043660617455',
    projectId: 'first-app-c060d',
    databaseURL: 'https://first-app-c060d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-c060d.appspot.com',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTSw5n0xGtB-o4Q4-sn_pqpnGNjs14HIA',
    appId: '1:1043660617455:ios:3840e37def347e0dea0d1a',
    messagingSenderId: '1043660617455',
    projectId: 'first-app-c060d',
    databaseURL: 'https://first-app-c060d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-c060d.appspot.com',
    iosBundleId: 'com.example.daftarBelanja.RunnerTests',
  );
}
